.travis.yml
Since now I'm running travis jobs on my repo, it's necessary to exclude development branches from travis runs.
=> don't run travis jobs on development branches

tlslite/errors.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/tlsrecordlayer.py, unit_tests/mocksock.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsrecordlayer.py
Prepare `TLSRecordLayer` for moving encryption and decryption to external class.
unit test coverage for sending and receiving records through socket, minimal test coverage for TLSRecordLayer (using private methods).
=> [v5] Small TLSRecordLayer refactor

tlslite/errors.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/mocksock.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsrecordlayer.py
Move record encryption and decryption to separate class, put it under full unit test coverage.
Rebased on top of current master, together with changes from pull #5 (commits since 9fc246c are the real addition).
=> [v3] Record layer refactor

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/session.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_recordlayer.py
Implements the encrypt then MAC mechanism for CBC based cipher suites in TLS from RFC 7366.
=> Implement RFC 7366 - Encrypt-then-MAC

README.md, tlslite/defragmenter.py, tlslite/recordlayer.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_defragmenter.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsrecordlayer.py
Implement RFC 5246 Section 6.2.1
Fragment writes that are above the 2^14 byte limit to smaller Record Layer messages (previously that was the case only for Application Data, now it applies to Handshake protocol too)
Support reading of fragmented messages and multiple messages of same type in single Record Layer message.
=> Support for message fragmentation

README.md, tlslite/constants.py, tlslite/messages.py, tlslite/recordlayer.py, unit_tests/test_tlslite_messages.py
Clean up code in CipherSuite, ClientKeyExchange and ServerKeyExchange
- add documentation for the above classes
- fix incorrect signing and signature verification of SRP_SHA_RSA ciphersuites in TLS < v1.2.
=> Clean up CipherSuite, CKE, SKE

README.md, tlslite/constants.py, tlslite/messages.py, tlslite/recordlayer.py, unit_tests/test_tlslite_messages.py
add unit tests for the above two messages
=> CertificateRequest and CertificateVerify test coverage

Makefile, scripts/tls.py, tlslite/handshakehashes.py, tlslite/messages.py, tlslite/messagesocket.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakehashes.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_messagesocket.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsconnection.py, unit_tests/test_tlslite_tlsrecordlayer.py
* add reporting of cipher name to `tls.py`
* actually support requesting of client cert in `tls.py`
* make optional parameters to ServerHello really optional (1st step to depreciate them)
* trivial fixups in Makefile
* rename `sendMessage` and `recvMessage` since they don't handle messages, just record payloads
* implement an easier-to-work-with abstraction on top of record layer - `MessageSocket` that does automatic defragmentation and allows for bundling messages together
* extra test coverage for recordlayer (AEAD/AES128GCM ciphers)
* extra test coverage for TLSExtension
* put all handshake hash updates into a single place
=> Little cleanup

tlslite/constants.py, tlslite/extensions.py, tlslite/messages.py, tlslite/tlsconnection.py, tlslite/utils/codec.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_utils_codec.py
- don't send empty SNI extension if no name specified
- fix parsing of server side reply to server_name extension
- add supported_groups, supported_point_formats, signature_algorithms and renegotiation_info extensions
- more test coverage
=> Extension fixes and additions

tlslite/extensions.py, tlslite/messages.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py
Since most of the library (especially the already released code) is using camelCase, use it for classes introduced past v0.4.8 to preserve style.
No logic changes, full unit test coverage for modified code.
=> Fix new field and method names to use camelCase

tlslite/recordlayer.py, unit_tests/test_tlslite_recordlayer.py
adds test cases for "no pad length byte"
since the MAC-then-Encrypt code was rewritten to fix Lucky 13
it wasn't vulnerable, only the Encrypt-then-MAC remained vulnerable,
this fixes this issue
=> fix CVE-2015-3220

.travis.yml, build-requirements.txt
because coverage 4.0 is officially incompatible with
Python 3.2, we must install older version of it when
running on Python 3.2
=> fix python3.2 builds

tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py
Because tlslite-ng did filter out only RC4 ciphers when checking for EtM, this meant that it looked like EtM was negotiated for AEAD and NULL ciphers too.
this patch set resolves this issue
=> Fix issue where Encrypt-then-MAC was technically negotiated with AEAD ciphersuites

tlslite/integration/asyncstatemachine.py
AsyncStateMachine doesn't work in py3 since the code has invalid syntax in py3, this pull fixes it.
=> Fix generators to work in python3

.travis.yml
workaround the sslv2 issue that made using current m2crypto impossible
on ubuntu
=> using rc of m2crypto

tlslite/tlsconnection.py
the signatures in TLSv1.2 follow the full PKCS#1 v1.5 spec, that means
that the encrypted value needs to include the prefix
tested for interoperability with GnuTLS both in TLS1.2 and TLS1.1,
with and without certificates
=> fix SRP-RSA, for real this time

tlslite/recordlayer.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_utils_constanttime.py
To make unit testing a bit cleaner and make a API promise for `tlsfuzzer`, expose the key private methods for handling MAC values and padding in CBC ciphers.
=> Expose some record layer private methods

tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/utils/chacha.py, tlslite/utils/chacha20_poly1305.py, tlslite/utils/cipherfactory.py, tlslite/utils/poly1305.py, tlslite/utils/python_chacha20_poly1305.py, unit_tests/test_tlslite_utils_chacha.py, unit_tests/test_tlslite_utils_chacha20_poly1305.py, unit_tests/test_tlslite_utils_poly1305.py
=> Implement the ChaCha cipher

tlslite/recordlayer.py, unit_tests/test_tlslite_recordlayer.py
Add support for getting the size of the used block cipher for bulk encryption, makes unit tests not depend on private fields and is useful for overriding behaviour of padding method in general
=> Add support for getting the block size

.landscape.yaml, .pep257
both when running standalone and when running as part
of prospector tool
We ignore D203 because it conflicts with the newer D211,
the former requires 1 whiteline before class doc text while
the latter requires no whitelines before class doc text
=> pep257 configuration

tlslite/constants.py, tlslite/extensions.py, tlslite/handshakehelpers.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakehelpers.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_tlsconnection.py
Implements TLS extension described in RFC 7685 that can be used to pad a ClientHello with sized between 256 and 511 bytes in order to avoid implementation bugs caused by certain ClientHello sizes.
fixes #63
=> Padding extension support to tlslite

pylintrc, tlslite/extensions.py, unit_tests/test_tlslite_extensions.py
since the on-the-wire encoding of those extensions is (almost)
identical, we can create an "abstract" extension that implements them
all and just depends on specific initialization
=> Extensions deduplication

tlslite/constants.py, unit_tests/test_tlslite_constants.py
because both the `__dict__` and `vars()` return the values
of the current class, not all the classes in hierarchy, we need to
manually traverse the hierarchy and collect all the fields ourselves
this allows for extending the subclasses of TLSEnum subclasses and
making both toRepr() and toStr() continue to work
=> allow subclassing TLSEnum subclasses

pylintrc, tlslite/handshakehashes.py, tlslite/mathtls.py, tlslite/recordlayer.py, tlslite/utils/cryptomath.py, tlslite/utils/tlshashlib.py, unit_tests/test_tlslite_utils_constanttime.py, unit_tests/test_tlslite_utils_cryptomath_m2crypto.py, unit_tests/test_tlslite_utils_tlshashlib.py
there are some additional limitations on behaviour of `m2crypto` and `hashlib` when system is working in FIPS mode - workaround those
=> Fix library in FIPS mode

unit_tests/test_tlslite_utils_cryptomath_m2crypto.py
because we're messing with how the whole module behaves, regular
mock.patch cannot clean up after us, as such we need to reload
the whole module after the testing is done to not affect other
tests
=> fix testing of FIPS workaround

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/mathtls.py, tlslite/session.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_mathtls.py, unit_tests/test_tlslite_session.py, unit_tests/test_tlslite_tlsconnection.py
=> support for extended master secret, RFC 7627

.travis.yml
Looks like hypothesis 3.x have removed support for Python 2.6,
try to workaround it by using older version
=> Workaround hypothesis on python 2.6

tlslite/utils/chacha.py
Using the following microbenchmark:
```
PYTHONPATH=. python2 -m timeit -n 10000 -r 10 \
--setup "from tlslite.utils.chacha import ChaCha;
cc = ChaCha(bytearray(32), bytearray(12));
e = bytearray(b'some text for encryption with a bit more text than a single block')"\
"cc.encrypt(e)"
```
The following changes make ChaCha20 implementation 1.8 times faster compared to current `master`. 425 usec vs 231 usec per loop on my machine.
=> Chacha20 speedup

unit_tests/test_tlslite_utils_constanttime.py
Tests from constanttime module using huge number of tested values
took signifficant amount of time. This is now reduced using package
hypothesis by testing only extreme values and a fixed number (200)
of randomly chosen values.
fixes #84
=> unit_test: constanttime module tests accelerated

tlslite/utils/aesgcm.py
read the object reference before the loop and not every-time inside it.
=> Optimization improvements

tlslite/constants.py
since we support both RFCs we should be able to identify
alert descriptions from them too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/101)
=> add alerts from RFC 5246 and 6066

tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/recordlayer.py, unit_tests/test_tlslite_recordlayer.py
Since draft-ietf-tls-chacha20-poly1305-00 is no longer valid, we need to update the code to handle the new standard.
fixes #56
fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/91)
=> Update ChaCha20 cipher definitions

tlslite/utils/compat.py
The python on Debian 7 (Wheezy) is closer to 2.6 than to 2.7,
for example struct.pack requires str() and will not accept
bytearray().
make the compat26Str() handle this old python correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/129)
=> python 2.7.3 compatibility

tlslite/keyexchange.py, tlslite/tlsconnection.py
The main changes are in _serverAnonKeyExchange in parts `if cipherSuite in CipherSuite.ecdhAnonSuites:`.
`else:` part is same as it was (ADH support).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/111)
=> Support for AECDH key exchange on server side

tlslite/constants.py
make all types in constants inherit from TLSEnum so that those values can be mapped back to names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/142)
=> make all types inherit from TLSEnum

unit_tests/test_tlslite_utils_cryptomath.py
If we fix isPrime() method, it needs to detect all known strong pseudoprimes,
not only the smallest known.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/144)
=> Add more strong pseudoprimes in tests

tests/tlstest.py
the DBM module on Windows creates databases as .dat files
by default (even if the original filename did not include it)
so retry deleting alternative name if the original one failed
fixes #162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/164)
=> remove correct file on Windows

scripts/tls.py, tlslite/integration/clienthelper.py, tlslite/tlsconnection.py, tlslite/utils/dns_utils.py, unit_tests/test_tlslite_tlsconnection.py, unit_tests/test_tlslite_utils_dns_utils.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/148)
=> Sanity checking in SNI

tlslite/tlsconnection.py
since the extension is specified as:
```
opaque ProtocolName<1..2^8-1>;
struct {
ProtocolName protocol_name_list<2..2^16-1>
} ProtocolNameList;
```
empty list or empty protocol name is a protocol violation, as
such, it should cause sending a decode_error alert
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/150)
=> send correct alerts in case the ALPN ext is malformed

tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py
Fix handling of resumption with Extended Master Secret (do advertise its use in Server Hello) and handle the case if a non EMS session is resumed with EMS advertised.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/160)
=> Extended Master Secret fixup

tlslite/keyexchange.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_keyexchange.py
* verify that EMS extension is properly formatted
* negotiate ECDHE even if client didn't advertise any curves, assume P-256 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/168)
=> fixup EMS and ECDHE without extensions

tlslite/handshakesettings.py, tlslite/keyexchange.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_handshakesettings.py
The ECC TLS RFC states that if the client doesn't advertise
any curves, it means that it supports any and the server
can then select any curve. That was OK when there was only
one set of curves supported in TLS. Now we have the legacy
curves, brainpool curves and djb (x25519 and x448) curves,
meaning that client that doesn't advertise any curves is likely
to support only the legacy curves, not the newer ones.
Thus we need to separate the default curve from most wanted
curve as the former must be most compatible while still
relatively secure while the latter can be fastest or most
secure, but will be negotiated only when client also supports
it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> default to a common curve if no curves advertised

tlslite/constants.py, tlslite/handshakesettings.py, tlslite/keyexchange.py, tlslite/utils/cryptomath.py, tlslite/utils/x25519.py, unit_tests/test_tlslite_keyexchange.py, unit_tests/test_tlslite_utils_cryptomath.py, unit_tests/test_tlslite_utils_x25519.py
add support for X25519 and X448 key exchange
Closes #89 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/154)
=> RFC7748 and RFC4492bis - X25519 and X448

tlslite/utils/pycrypto_rsakey.py
PyCrypto on Python 2.7 expects longs not only for initialisation
of RSA keys but also for RSA operations - fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/177)
=> fix long for pycrypto

.codeclimate.yml, tlslite/messages.py, unit_tests/test_tlslite_messages.py
100% test coverage for the `tlslite.messages` module, with the exception of TACK handling.
Fixing few minor bugs related to the old API handling.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/178)
=> Test coverage for tlslite.messages module, minor fixes

.codeclimate.yml
Allow for larger pieces of code to be duplicate - because of the code structure necessary for generators we have fairly large amounts of false positives for duplicate code detection.
Also cause a new coverage rebuild - coverage.io now supports monitoring of branch coverage and inclusion of it in the coverage measurement, so we need to rebuild the data and get a new baseline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/179)
=> CI updates

tests/tlstest.py
Improvements on precision of Throughput Measuring Mechanism. 
- Usage of timeit.default_timer() in tlstests.py instead of time.time(). 
- Measuring of the size for travelling data with the sys.getsizeof().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/183)
=> Improvements on precision of Throughput

tlslite/utils/python_rsakey.py, unit_tests/test_tlslite_utils_rsakey.py
For initialising the private key, only p and q are necessary.
If other values are not provided, calculate them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/184)
=> Initialise CRT values when not all provided in pycrypto RSA

pylintrc
Options `required-attributes` and `ignore-iface-methods` will be removed in version 2.0, they are Zope specific anyway, so we can remove them now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/186)
=> remove deprecated options from pylint config

tlslite/keyexchange.py, unit_tests/test_tlslite_keyexchange.py
TLS 1.3 requires that both the public value and the shared value to
be left-padded with zeros to the size of the prime used as the group
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/193)
=> TLS1.3 changes to FFDH

tlslite/recordlayer.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_recordlayer.py
Because tools like tlsfuzzer need to be able to send records with
arbitrary versions, without hiding content type, we need to restore
the API compatibility, in that if just the .version is set to high
values (3, 5), (3, 255), etc. the record layer behaves the same as it
did in TLS 1.2 and earlier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/197)
=> restore API compatibility for RecordLayer

scripts/tls.py
since caching and fragmentation is done on record
layer anyway, doing it on TCP level just screws with
alert delivery
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/199)
=> disable Nagle algorithm in example script

tlslite/recordlayer.py, unit_tests/test_tlslite_recordlayer.py
as the method of encrypting applies to the cipher, not
the connection or session, it needs to be kept together
with the cipher settings for a specific connection direction
fixes issue with EtM negotiation in renegotiation case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/201)
=> make setting the encryptThenMAC apply since next cipher change

.travis.yml, tlslite/utils/compat.py, tlslite/utils/cryptomath.py, tlslite/utils/openssl_aes.py, tlslite/utils/openssl_rsakey.py, tlslite/utils/openssl_tripledes.py, unit_tests/test_tlslite_utils_cryptomath.py, unit_tests/test_tlslite_utils_keyfactory.py
Since M2Crypto now supports Python3, test with it installed, also fix few minor issues related to that change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/204)
=> Python3 m2crypto

tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_recordlayer.py
fixes #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/217)
=> TLS 1.3 padding support

.travis.yml, docs/tlslite.utils.deprecations.rst, docs/tlslite.utils.rst, pylintrc, tlslite/defragmenter.py, tlslite/utils/deprecations.py, unit_tests/test_tlslite_utils_deprecations.py
old code used camelCase for attributes and method names, that's unpythonic
add decorators that allow us to retain API while changing names of those identifiers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/218)
=> deprecate non-pythonic names

.travis.yml, setup.py, tlslite/integration/asyncstatemachine.py, tlslite/tlsconnection.py
In python 3.7, async and await are new reserved keywords which cannot
be used as variable names or arguments. This commit renames some
parameters called async to comply with that. It also updates metadata
identifiers to state python 3.7 support as well as runs with mentioned
version on travis.
(fixed'up #216, fixes #214 )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/221)
=> Fixes for python 3.7 support

tests/tlstest.py
SRP db test case likes to timeout (about 1% failure rate on Travis) during synchronisation step, report the timing information of it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/226)
=> add debugging info to SRP db test case

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakehelpers.py, tlslite/handshakesettings.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/session.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_handshakehelpers.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py
Work in progress on TLS 1.3 support.
Includes:
- messages themselves
- documentation
- test cases
- key types:
Will fix #39 once ready
more clever ciphersuite selection (for external PSKs) will be handled in #213 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/174)
=> Mandatory parts of TLS 1.3

tlslite/utils/constanttime.py, unit_tests/test_tlslite_utils_constanttime.py
off-by-one error on mac checking, if the padding is of
minimal length (a single 0x00 byte), the mac is not
checked and thus the return value (`result`) is never falsified
this fixes the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/234)
=> verify the mac even if the padding is 1 byte long

tests/tlstest.py
because of issues like the ones in #219 the test runs
sometimes fail (with logging indicating very slow disk
access on slow machine), try increasing the timeout to
combat this
also add logging to show how long the client really waited
before aborting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/238)
=> increase timeout for SRP (db) case

tlslite/messages.py, unit_tests/test_tlslite_messages.py
`certChain` was a regular variable so we need to retain a setter for it (lack of it breaks `cipherscan`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/239)
=> fix API break in certChain property

unit_tests/test_tlslite_utils_keyfactory.py
the different behaviour was introduced in 0.28.0, not
in 0.27.0, so the test needs to check against 0.28.0
also (0, 27, 0) > (0, 27) evaluates to True
(this is where the original confuson came from)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/232)
=> fix M2Crypto 0.27.0 test compatibility

tlslite/tlsconnection.py
Now the connection is closed at the beginning if there is no common signature algorithms.
This fix is due to new test-scirpt (https://github.com/tomato42/tlsfuzzer/issues/209).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/244)
=> Move server key exchange sig

tlslite/utils/cipherfactory.py, tlslite/utils/python_tripledes.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_utils_tripledes.py
This is the very first edition to triple DES. python_tripledes.py contains three classes, so it needs compress to one (optionally isolate the python_des.py file) code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/202)
=> 3DES implementation

tlslite/tlsconnection.py
The merge https://github.com/tomato42/tlslite-ng/pull/244 introduced regressions to tlsfuzzer.
To fix this, we need to abort the connection earlier in TLS1.3 and later in TLS1.2.
So a condition was added to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/247)
=> fix server key exchange sig for TLS1.3, TLS1.2

scripts/tls.py, scripts/tlsdb.py
raise expects only certain object types as argument,
fix the raised exceptions in `tls.py` and `tlsdb.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/248)
=> fix type of raised object

tlslite/tlsrecordlayer.py
because the check for empty application data was before
the check for acceptable types, the empty application
data messages were accepted in the middle of handshake, this
fixes that
fixes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/260)
=> honour the expected type when receiving messages

.travis.yml, tlslite/tlsconnection.py
fixes #254 
* `supported_versions` can be used to negotiate pre TLS 1.2 version
* `supported_version` must list a recognised version for the negotiation to be successful
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/257)
=> TLS 1.3 version negotiation fixes

tlslite/tlsrecordlayer.py
TLS 1.3 states that to zero-length records the
implementation needs to reply with "unexpected_message"
alert
also fix typo in reference
fixes #255
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/259)
=> fix alert for zero-length records

scripts/tls.py
Now the header and body of HTTP response is buffered and sent as one message for python3.6
fixes #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/261)
=> fix python36 application data expectation

tlslite/constants.py
since those IDs are useful for scanners and fuzzers,
keep them in single place, in tlslite-ng
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/264)
=> add handshake types from draft TLS 1.3 versions

.travis.yml, Makefile, build-requirements.txt, tests/tlstest.py
Make coverage reporting (coveralls) run again on Python2.6 and Python3.2
collect coverage also from runs of the old test suite
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/269)
=> Coverage fixes

scripts/tls.py, tlslite/recordlayer.py, tlslite/utils/constanttime.py
fix handling of the padding in SSLv3
the padding cannot be longer than a block in SSLv3, not the overall ciphertext size
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/271)
=> SSL3 pad size

scripts/tls.py
the PSK identity should be a byte string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/272)
=> fix PSK identity parsing in tls.py in python3

tlslite/keyexchange.py, unit_tests/test_tlslite_keyexchange.py
in TLS 1.3 the FFDH key share must be the size of the
prime while it could have been padded or had the zero
bytes truncated in TLS 1.2 and earlier
that means it needs to be passed as a bytearray to key
exchange handling methods while the it was passed as an
integer previously
make the funcion handle both inputs and verify the size
of the share in case of TLS 1.3-like call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/274)
=> fix FFDHE key exchange in TLS 1.3

tlslite/tlsconnection.py
When the Finished message is malformed, actually send the alert before closing the connection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/276)
=> Send alert for malformed finished

tlslite/utils/cryptomath.py, unit_tests/test_tlslite_utils_cryptomath.py
Increase test coverage for cryptomath.py module, remove dead code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/281)
=> Test coverage for cryptomath

scripts/tls.py, tlslite/tlsconnection.py
Few simple fixes:
- tell kernel to deliver all queued data on connection close
- don't send duplicate ids in supported_groups in Encrypted Extensions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/284)
=> Simple fixes

tlslite/utils/python_tripledes.py, unit_tests/test_tlslite_utils_tripledes.py
make the pure 3des python implementation behave the same way the other 3des implementations do
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/292)
=> pure-python 3des bytearray

tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_recordlayer.py
even if server does not support 0-RTT it needs to be able to process it correctly
fix #290 
tested by https://github.com/tomato42/tlsfuzzer/pull/423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/293)
=> 0-RTT tolerance

tlslite/utils/python_rsakey.py
because the same key can be used by server handling multiple
clients, the private key op must be multithread safe
as the blinding value can be generated by multiple threads calling
the method at the same time, or it can be later updated twice while
the unblinder is updated just once (and similar concurency issues)
all those operations need to be handled in a single thread at a time
alternative would be to generate a blinder and unblinder for every call,
hard to say what would scale better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/297)
=> make Python_RSAKey multithread safe

tlslite/tlsconnection.py
When tlslite-ng detected invalid key_share, it just raised `TLSIllegalParameterException` but did not send this alert to client.
This PR should fix this.
fix for testing https://github.com/tomato42/tlsfuzzer/issues/273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/304)
=> send alert msg about invalid key_share

build-requirements-2.6.txt
new version dropped support for 2.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/312)
=> use pycparser compatible with py2.6

scripts/tls.py
more complex testing requires support for loading a full chain of
certificates and sending them to the client. Add support for that in
`tls.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/313)
=> allow reading a chain of certificates with -c option

tlslite/ocsp.py, tlslite/x509.py, unit_tests/test_tlslite_ocsp.py, unit_tests/test_tlslite_signed.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/315)
=> Ocsp bind to cert

tlslite/tlsconnection.py
the `Session.tickets` and `TLSConnection.tickets` should be one and the same object, that means, the `tickets` need to always be provided to the session constructor
fixes #317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/318)
=> always duplicate tickets when creating a new session

tlslite/utils/rsakey.py
the signature and encryption operations are defined in terms of
bytes, not text-strings, so make it explicit in docs
fixes #320 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/321)
=> document that all RSA key operations are on bytes

build-requirements-2.6.txt, unit_tests/test_tlslite_utils_deprecations.py
new idna dropped suppport for 2.6 so use the old one
there are also problems with warnings module on py3.2 and py3.3 so fix them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/323)
=> fix Python 2.6 builds

scripts/tls.py, tlslite/constants.py, tlslite/tlsconnection.py
implement support for downgrade sentinel and allow for testing its behaviour with older protocol versions in tlsfuzzer
this is part of work towards #306 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/324)
=> TLS1.3 downgrade sentinel

scripts/tls.py, tlslite/utils/compat.py
time.clock() was deprecated since Python 3.3, with time.perf_timer() taking its place.  In versions of Python where both exist, they act identically.  
Created a function timeStamp() which determines which of these to use based on the running Python version.  Replaced all instances of time.clock() with timeStamp().
fixes #327 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/330)
=> Replaced time.clock() with timeStamp()

tests/tlstest.py, tlslite/tlsconnection.py
fix incorrect alerts and minor incompatibility with handling resumption
necessary to make tests added in https://github.com/tomato42/tlsfuzzer/pull/487 pass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/334)
=> Resumption cipher mismatch

tests/tlstest.py, tlslite/constants.py, tlslite/keyexchange.py, tlslite/messages.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_keyexchange.py, unit_tests/test_tlslite_messages.py
Fixes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/333)
=> Add support for CertificateRequest (TLS 1.3)

tlslite/tlsconnection.py
Shows up as a failure to assign to a tuple in tests that intentionally
break session tickets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/336)
=> Fix bug when returning errors for _tryDecrypt

tlslite/tlsconnection.py, tlslite/utils/keyfactory.py, tlslite/utils/openssl_rsakey.py, tlslite/utils/pycrypto_rsakey.py, tlslite/utils/python_rsakey.py, tlslite/utils/rsakey.py, tlslite/x509.py
make server use client provided certificate to check if it selected correct signature algorithm, abort if it didn't
also minor clean ups of related modules
fixes #279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/337)
=> Fix tests of key type used for verification

tests/tlstest.py, tlslite/constants.py, tlslite/extensions.py, tlslite/handshakesettings.py, tlslite/messagesocket.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py
Implement record size limit extension from RFC 8449.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/338)
=> Record size limit extension

tlslite/tlsconnection.py
We were not passing the protocol version to _sigHashesToList so
the fucntion was not stripping pkcs1 signature schemes and allowing
them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/339)
=> Fix TLS1.3 handshakes to refuse pkcs1 signatures

tlslite/keyexchange.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_keyexchange.py
Misc fixes to minor bugs uncovered while working on https://github.com/tomato42/tlsfuzzer/pull/496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/340)
=> Misctls13fixes

scripts/tls.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py
support for sending multiple messages of the same type in single record,
coalesce the server encrypted flight and session tickets, when
there are multiple to be sent
add support for sending multiple session tickets
rework key derivation for session tickets to prevent IV collisions
fixes #286 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/287)
=> Send handshake messages in as few records as possible, send multiple new session tickets

scripts/tls.py, tlslite/handshakesettings.py, unit_tests/test_tlslite_handshakesettings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/347)
=> allow setting 0 tickets to disable sending tickets in TLS 1.3

README.md, SECURITY.md
Provide the security policy in place that GitHub expects it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/351)
=> move security policy to separate file

tlslite/constants.py
Fix comment typo in constants.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/352)
=> fix comment typo

tlslite/mathtls.py, tlslite/utils/cryptomath.py, tlslite/utils/tlshmac.py
on new FIPS compliant Python HMAC is implemented as a thin wrapper around
openssl implementation of HMAC, that makes it impossible to add a
field to the hmac object or use MD5 for hmac-ing in FIPS mode
so re-implement HMAC in pure python (still use native hash implementations)
leave implementation of fallback for later:  #356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/355)
=> make HMAC work in strict FIPS mode

tlslite/messages.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_messages.py
extend heartbeat support so that it can be used in tlsfuzzer
fix few issues with message handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/357)
=> fixups to heartbeat support

requirements.txt
CVE-2019-14853 impacts the tlslite-ng (it's how we found it in the
first place), so do ensure that we're using version that doesn't make
tlslite-ng vulnerable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/361)
=> as ecdsa 0.13.3 fixes CVE-2019-14853, we need it

tlslite/constants.py, unit_tests/test_tlslite_constants.py
Useful for tools like tlsfuzzer and cipherscan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/363)
=> add EdDSA sigalg definitions

tlslite/messages.py, unit_tests/test_tlslite_messages.py
Add ability to handle HelloRequest messages, mostly for tlsfuzzer to be able to handle renegotiation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/354)
=> add HelloRequest message object

scripts/tls.py, tests/tlstest.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py, tlslite/x509.py, tlslite/x509certchain.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_x509.py
- moved to #367
-  (partially: see #366)
fixes #52 
merged as #359,  #360, #361, #363
------------------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/196)
=> ECDSA support

tlslite/extensions.py, tlslite/utils/codec.py, unit_tests/test_tlslite_messages.py
Make the errors reported by tlslite-ng when the exceptions are malformed more readable
Work towards  #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/371)
=> more readable error messages for malformed exceptions

Makefile, scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_messages.py
Support for handling KeyUpdate post-handshake msg.
fixes #210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/341)
=> Post handshake KeyUpdate support

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/errors.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py
add support for Post Handshake Authentication (the post_handshake_auth extension)
depends on #196 and #341 
fixes #208 
TODO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/350)
=> Post handshake auth

scripts/tls.py
since with request_pha we send the CertificateRequest always,
if we combine it with `/secret` we end up with two requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/379)
=> do not send two PHAs

tlslite/utils/openssl_tripledes.py, tlslite/utils/python_tripledes.py, unit_tests/test_tlslite_utils_tripledes_split.py
Two 3DES fixes - one for the Python implementation, one for the M2Crypto one - and a new test.
```
commit 5c4078185500f835a12423c6bd5b863681c44b08
Fix IV handling for 3DES, test consecutive calls
Correctly set IV for consecutive 3DES encrypt/decrypt invocations.
Test that the results of three invocations yield the same result
as a combined single one, cross-check this across three implementations.
```
```
commit 8f1fa9bec91ca8c83c77142a3ffb6a5c78e73586
Streamline M2Crypto 3DES IV handling
M2Crypto defaults to padding the ciphertext,
and the previous implementation danced around that awkwardly
by padding and unpadding ciphertext on decryption
and updating the IV manually.
`m2.cipher_set_padding(context, 0)`
allows to shoulder the IV handling back to where it belongs
and to get rid of …
```
=> 3des fixes

tests/tlstest.py, tlslite/tlsrecordlayer.py
with HTTP flows and PHA we need some special handling of KeyUpdate
so add it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/380)
=> fix PHA with KeyUpdate with HTTP

tlslite/keyexchange.py, tlslite/tlsconnection.py, tlslite/utils/ecc.py
fix handling malformed ECDH key shares and malformed key_shares extension
don't create malformed ones ourselves
fixes bugs identified by https://github.com/tomato42/tlsfuzzer/pull/553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/388)
=> TLS 1.3 ECDH and key_shares fixes

tlslite/constants.py, tlslite/tlsconnection.py
fixes #389 
tested by https://github.com/tomato42/tlsfuzzer/pull/540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/390)
=> check if client doesn't advertise in TLS 1.3 groups forbidden in TLS 1.3

tests/tlstest.py, tlslite/utils/aes.py, tlslite/utils/aesccm.py, tlslite/utils/aesgcm.py, tlslite/utils/cipherfactory.py, tlslite/utils/openssl_aes.py, tlslite/utils/openssl_aesccm.py, tlslite/utils/openssl_aesgcm.py, tlslite/utils/python_aes.py, tlslite/utils/python_aesccm.py, unit_tests/test_tlslite_utils_aescbc.py, unit_tests/test_tlslite_utils_aesccm.py, unit_tests/test_tlslite_utils_aesctr.py, unit_tests/test_tlslite_utils_aesgcm.py
Currently the CTR code is in aesgcm.py. Separate that code so it can be reused and modify the code in aesccm.py to use it.
Also add the NIST test vectors from 800-38A for CBC and CTR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/384)
=> Separate CTR code and replace it in AES-CCM and AES-GCM

build-requirements.txt, unit_tests/test_tls1_3_vectors.py
Fixes #308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/397)
=> Update test vector to released RFC version

.travis.yml, tlslite/utils/cryptomath.py
fixes #198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/408)
=> detect pycryptodome, don't use it

tlslite/utils/aesccm.py, tlslite/utils/openssl_aes.py, unit_tests/test_tlslite_utils_aesccm.py
fixes #406 
The first issue was that the CBC IV was not reset properly which is now handled by the setter.
The second issue was with the _8 ciphers where the authentication value was not padded before going through CTR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/410)
=> fix aesccm when using m2crypto

tlslite/utils/cryptomath.py, tlslite/utils/openssl_aes.py
fixes #405 
It looks like AES-CTR was introduced in m2crypto version 0.25.0
This adds a method to check if the ciphers are supported and if not, it falls back to the python implementation for that cipher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/411)
=> check if the ciphers are supported by m2crypto before using them

.travis.yml, scripts/speed.py, scripts/tls.py, tlslite/api.py, tlslite/utils/cryptomath.py, tlslite/utils/python_rsakey.py
profile and speed up RSA operations, add support for gmpy2 for operations
also add tool for benchmarking
fixes #375 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/415)
=> Quicker RSA operations

tlslite/bufferedsocket.py, tlslite/defragmenter.py, tlslite/mathtls.py, tlslite/utils/asn1parser.py, tlslite/utils/codec.py, tlslite/utils/compat.py, tlslite/utils/cryptomath.py, tlslite/utils/rsakey.py, tlslite/utils/tlshmac.py, unit_tests/test_tlslite_bufferedsocket.py
Optimise methods and functions used heavily in a handshake.
Speeds it up by about 25%
fixes #356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/419)
=> Faster handshake

tlslite/constants.py
Add  constants for `rsa_pkcs1_md5` x509 certificates
The `test_toRepr_with_obsolete_value` test fails because of the added value, I'm not too sure if it's by design or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/429)
=> Add support for RSA PKCS1 MD5 in x509 certificates

tlslite/integration/imap4_tls.py
fixes the
```
File "/home/hkario/dev/tlslite-2/tlslite/integration/imap4_tls.py", line 83, in __init__
IMAP4.__init__(self, host, port)
File "/usr/lib64/python3.9/imaplib.py", line 202, in __init__
self.open(host, port, timeout)
TypeError: open() takes from 1 to 3 positional arguments but 4 were given
```
error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/434)
=> fix the imaplib error with python3.9

tlslite/utils/constanttime.py, tlslite/utils/keyfactory.py, tlslite/utils/openssl_rsakey.py, tlslite/utils/python_key.py, tlslite/utils/rsakey.py, unit_tests/test_tlslite_utils_constanttime.py, unit_tests/test_tlslite_utils_rsakey.py
currently we leak severely where the issue is in the padding check of RSA decryption, so attempt depadding in side-channel free way (at least to the degree that Python allows)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/438)
=> Attempt side-channel free RSA decryption

tlslite/utils/compat.py, tlslite/utils/constanttime.py, tlslite/utils/keyfactory.py, tlslite/utils/openssl_rsakey.py, tlslite/utils/python_key.py, tlslite/utils/python_rsakey.py, tlslite/utils/rsakey.py, unit_tests/test_tlslite_utils_constanttime.py, unit_tests/test_tlslite_utils_rsakey.py
Attempt fixing the Bleichenbacher side-channel leaks.
backport of the #438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/439)
=> Bleichenbacher fixes [0.7]

.travis.yml
looks like M2Crypto 0.37.0 broke a lot of things so use something
older
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/442)
=> use old M2Crypto with old(er) pythons

.github/workflows/ci.yml, build-requirements.txt
older pythons correctly compare the the branch to master and report the change in coverage, but not the new versions, see what happens if we try old coveralls on new pythons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/453)
=> Unify reports with py2 and py3 coverage in coveralls

.github/workflows/ci.yml, build-requirements-2.6.txt, build-requirements-3.3.txt, build-requirements-3.4.txt, build-requirements.txt
the curl trick to finish the run with merge doesn't work
(it does with pull_request though, go figure!), the problem is that
if we use new coveralls, it uses different build IDs so a new coveralls
can't finish a parallel run submission from old coveralls
use a fork on older pythons so that the IDs remain consistent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/458)
=> use new coveralls

tlslite/utils/compat.py, tlslite/utils/openssl_rsakey.py, unit_tests/test_tlslite_utils_rsakey.py
add few negative tests with zero padding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/448)
=> rsa: consistent handling of zero-padded ciphertext

tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_tlsconnection.py
Make tlslite-ng pass with current tlsfuzzer test suite (don't advertise DSA in CertificateRequest)
And fix issues around CCS in TLS 1.3:
- allowing CCS post handshake, fixes #316 
- sending CCS when client used empty session_id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/462)
=> Fixes for CCS and DSA

.github/workflows/ci.yml
PyPA is deprecating non-SNI access to the CDN, use wget to download packages instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/467)
=> workaround SNI deprecation for pip on py2.6

tlslite/mathtls.py
the function name is calc_key, not calcKey, and it's a function, not
a method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/463)
=> fix error messages for deprecated methods

.github/workflows/ci.yml, tlslite/constants.py
RFC 4055 Section 2.1 allows both no parameters for AlgorithmIdentifier and NULL parameters, so accept both.
fixes #470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/471)
=> handle both missing parameters and NULL parameters for RSA-PSS

.github/workflows/ci.yml
As ubuntu 16.04 is getting removed from Actions, we need to use something newer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/474)
=> use newer ubuntu for old pythons

.github/workflows/ci.yml
github actions people decided that python2.7 is "persona non grata" so use the native python2.7 from the standard container that they do support...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/493)
=> fix CI with python2.7

tlslite/messages.py, unit_tests/test_tlslite_messages.py
Fix handling of multi-byte CCS messages, fixes #464
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/495)
=> detect malformed CCS messages

tlslite/constants.py, tlslite/defragmenter.py, tlslite/tlsrecordlayer.py
Handshake messages in general MUST NOT be interleaved with other record types, and messages that cause key changes MUST be aligned with a record boundary.
Fixes #342
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/496)
=> check handshake messages for interleaving and alignment in TLS 1.3

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/extensions.py, tlslite/handshakesettings.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/session.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py
This enables both client and server side to resume session using session tickets defined in RFC5077.
I have tested this against openssl and gnutls, both client and server side in tls1.2, tls1.1 and tls1.0 and it seems to be working.
To enable it on client side all you need to is initialize an empty list for connection.session_ticket_cache where the tickets received from server are held.
Example:
```
session_cache = []
connection.session_ticket_cache = session_cache
```
To enable it on server side you need to generate the encryption keys that are held in settings.session_ticket_keys.
Example:
```
settings.session_ticket_keys = {}
settings.session_ticket_keys["key_name"] = getRandomBytes(16)
settings.session_ticket_keys["aes_key"] = getRandomBytes(16) …
```
=> Implementation of RFC5077 SessionTickets resumption.

tlslite/recordlayer.py
In some situations, the other side of the connection may send an unencrypted alert when we expect encrypted messages, that causes the decryption to fail instead of returning the alert to the calling application.
Fixes #344
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/499)
=> allow unencrypted alerts just before encrypted messages

.github/workflows/ci.yml, tlslite/api.py, tlslite/utils/openssl_rsakey.py, unit_tests/test_tlslite_utils_keyfactory.py
Test with release version of python 3.12, work with newer m2crypto versions, workaround gmpy2 and py3.12...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/508)
=> Basic maintenance

tlslite/tlsconnection.py
Prevent the server from echoing the session_ticket extension when either ticket_count or ticketKeys are not set in the settings. Attaching capture of a conversation after the change between a tlslite server and openssl s_client. 
fixes https://github.com/tlsfuzzer/tlslite-ng/issues/524
[capture.pcap.txt](https://github.com/user-attachments/files/16588702/capture.pcap.txt)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/525)
=> Make RFC compatible behaviour with session ticket

tlslite/messages.py, tlslite/utils/compat.py, unit_tests/test_tlslite_utils_cryptomath.py
make int_to_bytes() and numberToByteArray() consistent with int().to_bytes() from python3, that means encoding zero as a single null byte, not as an empty byte string
also fix the bug hidden by it:
ClientKeyExchange: correctly detect too short key shares
the field for DH key shares is defined as
```
case explicit: opaque DH_Yc<1..2^16-1>;
```
so the share must be at least 1 byte long, update the code to abort if it is too short
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/527)
=> make int_to_bytes and numberToByteArray encode 0 as b'\x00'

tlslite/messages.py, unit_tests/test_tlslite_messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/531)
=> messages.py: handle empty compressed certificate message

.github/workflows/ci.yml, scripts/tls.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/keyexchange.py, tlslite/tlsconnection.py, tlslite/utils/compat.py, unit_tests/test_tlslite_keyexchange.py
after draft-kwiatkowski-tls-ecdhe-mlkem
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/530)
=> support for ML-KEM hybrid key exchange groups

docs/conf.py, tlslite/handshakesettings.py
fix docs generation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/532)
=> use new syntax for intersphinx links

scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py, tlslite/utils/ecc.py
Add support for Brainpool curves in TLS 1.3, both for ECDH and signing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/529)
=> add support for Brainpool curves in TLS 1.3 (RFC8734)

Makefile
build both the source distribution and a wheel
obsoletes #534
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/536)
=> use the new calling convention for setuptools

tlslite/utils/compat.py
On Python 2 the import succeeds, but then it errors out with SyntaxError, handle that gracefully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/535)
=> fail kyber_py import because of SyntaxError too

tlslite/tlsconnection.py
Stop the server accepting the legacy TLS 1.2 Brainpool group IDs in TLS 1.3, allow only TLS 1.3 specific group IDs.
Test coverage: https://github.com/tlsfuzzer/tlsfuzzer/pull/983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/539)
=> don't negotiate legacy brainpool IDs in TLS 1.3

.github/workflows/ci.yml, unit_tests/test_tlslite_utils_rsakey.py
More vectors and align them with the draft-irtf-cfrg-rsa-guidance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/541)
=> Additional test vectors for the RSA implicit rejection

.github/workflows/ci.yml
Code climate is no more so remove it to stop CI from failing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/557)
=> code-climate is dead, remove it
