tlsfuzzer/tlslite-ng

Makefile, README.md, scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakehashes.py, tlslite/handshakesettings.py, tlslite/mathtls.py, tlslite/messages.py, tlslite/messagesocket.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, tlslite/utils/cryptomath.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakehashes.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_mathtls.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_messagesocket.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsconnection.py, unit_tests/test_tlslite_tlsrecordlayer.py
* Implement support for SHA384 PRF, add ciphersuites which use it
* add support for NULL encryption
* add support for more anonymous DH suites
=> SHA384 PRF and NULL encryption

Makefile, README.md, scripts/tls.py, tests/tlstest.py, tlslite/constants.py, tlslite/handshakehashes.py, tlslite/handshakesettings.py, tlslite/mathtls.py, tlslite/messages.py, tlslite/messagesocket.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, tlslite/utils/constanttime.py, tlslite/utils/cryptomath.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakehashes.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_mathtls.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_messagesocket.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_tlsconnection.py, unit_tests/test_tlslite_tlsrecordlayer.py, unit_tests/test_tlslite_utils_constanttime.py
Fix the timing side channel in CBC padding check - at least as much as possible in pure python.
=> fix Lucky13

README.md, tests/tlstest.py, tlslite/__init__.py, tlslite/api.py, tlslite/handshakesettings.py
Don't accept or offer RC4 ciphers by default
closes #27
=> disable RC4 ciphers by default

tlslite/mathtls.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_mathtls.py
since it's a cryptographic calculation, it shouldn't be done inside
TLSConnection. Moving it out to a helper module also allows us to put
it under test coverage
=> refactor calcFinished out

unit_tests/test_tlslite_recordlayer.py
Since SSLv3 requires padding to be always minimal, make sure that's how the library behaves
=> add test if generated padding is minimal

.gitignore, .travis.yml, tlslite/utils/cryptomath.py, unit_tests/test_tlslite_utils_cryptomath.py
clean-up the numBits and numBytes functions
=> Numbits cleanup

.travis.yml, setup.py
test if the code is Python 3.5 compatible
=> make support for Python 3.5 official

tlslite/constants.py, unit_tests/test_tlslite_constants.py
add ability to perform reverse lookups for some IDs used in TLS like HashAlgorithms of record layer Content Type
=> Human readable reverse lookups for TLS IDs

tlslite/integration/clienthelper.py, tlslite/integration/httptlsconnection.py
Make HTTPTLSConnection automatically use the hostname for Server Name Indication
=> fix support for SNI in HTTPTLSConnection

tlslite/constants.py, unit_tests/test_tlslite_constants.py
we want to add elements of the list, not the list itself
=> fix GroupName brainpool curve IDs

tlslite/messages.py, unit_tests/test_tlslite_messages.py
since server_version is a tuple, it should be printed as such
=> ServerHello - print valid tuple for repr

tlslite/constants.py, tlslite/messages.py, tlslite/recordlayer.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py
Implement the bits necessary for external applications to perform SSLv2 negotiation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/92)
=> Implementation of SSLv2 record layer

tlslite/bufferedsocket.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_bufferedsocket.py
reduce number of system calls in the handshake phase by buffering the messages until we start waiting for the other side to respond
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/100)
=> Add socket buffering

.codeclimate.yml, CONTRIBUTING.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/102)
=> add markdownlint to codeclimate checker

scripts/tls.py, tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/utils/cryptomath.py, unit_tests/test_tlslite_tlsconnection.py
Implement the mechanism from [RFC5705](https://tools.ietf.org/html/rfc5705)
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/104)
=> Keying material exporter

CONTRIBUTING.md
fix #112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/113)
=> RHEL 7 dependencies

CONTRIBUTING.md
it's not exactly obvious what needs to be done after CI
reports errors or review indicates needed changes,
so spell those things out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/115)
=> information oh what to do after feedback

tlslite/keyexchange.py, unit_tests/test_tlslite_keyexchange.py
verification of RSA signatures + test cases for it
fixes #57 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/116)
=> fix of issue57

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/117)
=> add epydoc, and how to make it work

tlslite/utils/cryptomath.py, unit_tests/test_tlslite_utils_cryptomath.py
Test cases for HMAC
fixes  #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/119)
=> [WIP] HKDF implementation

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/123)
=> add info that hypothesis depends on enum34 on python2

tlslite/messages.py, unit_tests/test_tlslite_messages.py
if the NPN extension is provided in the `extensions` list, it will not be added to the client hello
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/118)
=> NPN extension fix

tlslite/messages.py
There are quite a few pep-8 and pep-257 mistakes, the code is also not shared between client hello and server hello, so fix those issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/122)
=> Style fixes for messages.py

tlslite/extensions.py, tlslite/keyexchange.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_keyexchange.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_tlsrecordlayer.py
fix few ways in which the tlslite-ng server is misbehaving - not sending extensions, not sending alerts, not verifying sizes of fields when it should, etc....
Fixes #114 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/121)
=> Various protocol fixes

tlslite/tlsrecordlayer.py, tlslite/utils/compat.py
Few things weren't fixed for python 3, address them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/126)
=> Python3 protocol fixes

scripts/tls.py, tlslite/constants.py, tlslite/extensions.py, tlslite/session.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_extensions.py
Add support for Application Layer Protocol Negotiation extension for TLS.
fix #64 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/132)
=> Support for ALPN extension from RFC 7301

tlslite/utils/asn1parser.py, tlslite/utils/codec.py
Document ASN1 and Parser classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/137)
=> Documentation and style fixes

tlslite/constants.py, tlslite/extensions.py, tlslite/messages.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py
Part of work towards #61, just message parsing for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/138)
=> Handling of OCSP staple extension and messages

tests/tlstest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/147)
=> increase timeouts for test connections

tlslite/keyexchange.py, unit_tests/test_tlslite_keyexchange.py
Check values for obvious small-subgroup values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/139)
=> DHE small subgroup checks

tlslite/errors.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py
more stringent tests for the received Client Hello message to align the implementation with the RFC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/141)
=> Parser fixes

.codeclimate.yml, tlslite/extensions.py, tlslite/messages.py, tlslite/utils/codec.py, unit_tests/test_tlslite_utils_codec.py
`codec.Writer` is used all over the tlslite-ng, unfortunately its methods are not too optimised, if not completely unoptimised
it means that creating large number of messages is relatively slow, so try to speed it up by either
introducing faster methods, or using faster methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/124)
=> Codec speedup

tlslite/messages.py, unit_tests/test_tlslite_messages.py
Because NSS zero-pads the key share in SKE message, the
writeParams and thus hash calculation for the message won't
match and the signature verification will fail
this patch extends the message parser to store the length
of the field together with value and recreate it on write
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/149)
=> SKE hash bug

tlslite/tlsconnection.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/165)
=> explain why the check is duplicate in tlsconnection

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/166)
=> post-merge changelog update

.travis.yml
Fixes: #163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/167)
=> add python 3.6 to .travis.yml

unit_tests/test_tlslite_utils_cryptomath.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/161)
=> add a big composite number to test the non-working of M-R primality test

tlslite/utils/rsakey.py, unit_tests/test_tlslite_utils_rsakey.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/169)
=> correctly handle errors from RSA_PSS verification

tlslite/tlsconnection.py
As suggested by @ueno in https://github.com/tomato42/tlslite-ng/pull/168#issuecomment-315298220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/170)
=> make ECDHE and FFDHE ciphersuite enabling more logical

tlslite/extensions.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_extensions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/171)
=> Be more strict about received SNI extensions

tlslite/utils/cryptomath.py, unit_tests/test_tlslite_utils_cryptomath.py
fix handling of null FFDHE parameters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/175)
=> FFDHE null params

tlslite/errors.py, tlslite/keyexchange.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_keyexchange.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/173)
=> correctly handle missing ecdh key share from CKE message

tlslite/extensions.py, unit_tests/test_tlslite_extensions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/152)
=> add repr() support to SignatureAlgorithmsExtension

tlslite/utils/pycrypto_rsakey.py
Sometimes pycrypto will raise a "ValueError: Message too large"
exception. Print debugging info when that happens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/181)
=> try to diagnose spurious ValueError raised by pycrypto

tlslite/constants.py, tlslite/extensions.py, tlslite/messages.py, unit_tests/test_tlslite_constants.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/180)
=> Add support for parsing and serialising TLS 1.3 messages and extensions

tlslite/utils/compat.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/182)
=> Jython2.7 bytearray bug fix.

tlslite/messages.py, unit_tests/test_tlslite_messages.py
add few changes that should have been part of #180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/185)
=> Messages fixups

tlslite/constants.py, tlslite/errors.py, tlslite/handshakesettings.py, tlslite/recordlayer.py, tlslite/utils/cryptomath.py, unit_tests/test_tls1_3_vectors.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_recordlayer.py, unit_tests/test_tlslite_utils_cryptomath.py
add support for TLS 1.3 key derivation function and record layer encryption
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/187)
=> TLS 1.3 record layer

tlslite/keyexchange.py, unit_tests/test_tlslite_keyexchange.py
extract the generic KEX calculation from < TLS1.2 message processing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/188)
=> KEX changes

tlslite/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/192)
=> Few constants for TLS1.3

tlslite/tlsrecordlayer.py, tlslite/utils/lists.py, unit_tests/test_tlslite_utils_lists.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/190)
=> Unexpected handshake error

tlslite/messages.py, unit_tests/test_tlslite_messages.py
For HRR ClientHello we will need to be able to compare old hello to new
hello, add methods to do that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/191)
=> allow comparing handshake messages

.travis.yml
Fix build environment compatibility with Python 2.6 and Python 3.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/203)
=> 2.6 & 3.3 compat

Makefile, tests/tlstest.py
some travis hosts are very slow, so try to
workaround it by insreasing timeouts in tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/215)
=> increase timeouts for iteraction

tlslite/x509.py
fixes #223 
fix the non-pythonic names for variables in the method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/224)
=> Fix Python2 compatibility with str

unit_tests/test_tlslite_utils_deprecations.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/222)
=> check if two deprecated_params can be used together

tests/tlstest.py, tlslite/constants.py, tlslite/extensions.py, tlslite/messages.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tls1_3_vectors.py, unit_tests/test_tlslite_constants.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_recordlayer.py
reviewed in https://github.com/tomato42/tlslite-ng/pull/174#issuecomment-370400026
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/225)
=> TLS 1.3 part 2

scripts/tls.py, tlslite/constants.py, tlslite/extensions.py, tlslite/handshakehelpers.py, tlslite/handshakesettings.py, tlslite/messages.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakehelpers.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_messages.py
reviewed in https://github.com/tomato42/tlslite-ng/pull/174#issuecomment-371195127 by @Jakuje
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/227)
=> TLS 1.3 part 3

tests/tlstest.py, tlslite/basedb.py
round two of debugging the hang of the SRP (db) test case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/228)
=> SRP db issue debugging

.travis.yml, README.md, docs/tlslite.utils.deprecations.rst, docs/tlslite.utils.rst, setup.py, tlslite/integration/asyncstatemachine.py, tlslite/tlsconnection.py, tlslite/utils/compat.py, tlslite/utils/deprecations.py, tlslite/x509.py, unit_tests/test_tlslite_utils_deprecations.py, unit_tests/test_tlslite_utils_keyfactory.py
backport few fixes from master (0.8) branch to the 0.7 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/229)
=> Backports to 0.7

unit_tests/test_tlslite_utils_keyfactory.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/230)
=> M2Crypto 0.27.0 behaves the same as 0.27.1

README.md
Go to https://github.com/tomato42/tlslite-ng/tree/nicer-readme to see how it's rendered
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/249)
=> make the readme a bit nicer

scripts/tls.py, tlslite/integration/tlsasyncdispatchermixin.py, tlslite/integration/tlssocketservermixin.py, tlslite/integration/xmlrpctransport.py, tlslite/messagesocket.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, unit_tests/test_tlslite_defragmenter.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_messagesocket.py, unit_tests/test_tlslite_tlsconnection.py, unit_tests/test_tlslite_tlsrecordlayer.py
fixes #242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/243)
=> Follow naming conventions

.travis.yml
fixes dependencies of other components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/258)
=> use py2.6 compatible inflect

tlslite/tlsconnection.py
send just one CCS message, either after HRR or SH, but not both
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/262)
=> do not send second CCS after ServerHello in HRR case

tlslite/extensions.py, tlslite/utils/codec.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_utils_codec.py
Add parser for the cookie extension, share code with the renegotiation_info extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/263)
=> Cookie extension parser

.travis.yml
report the test coverage to code climate too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/267)
=> add codeclimate test coverage

scripts/tls.py, tests/tlstest.py, tlslite/tlsconnection.py
fix few bugs in tlsconnection.py, extend test coverage for it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/270)
=> Fix issues and more tests in tlsconnection.py

tlslite/ocsp.py, tlslite/signed.py, unit_tests/test_tlslite_ocsp.py, unit_tests/test_tlslite_signed.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/240)
=> Add OCSP signature verification

tests/tlstest.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py, unit_tests/test_tlslite_handshakesettings.py
fixes #265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/266)
=> PSK key exchange

tlslite/tlsconnection.py
TLS 1.3 draft:
Any records following a Finished message MUST be encrypted under the
appropriate application traffic key as described in Section 7.2.
so change to ap traffic secret derived keys right after
processing the Finished message from server or after
sending a Finished message from server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/273)
=> switch to ap traffic keys for server after server Finished

tlslite/utils/chacha20_poly1305.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/277)
=> chacha20poly1305: constant time tag check

tlslite/utils/aesgcm.py
Sorry for another PR with the same thing, I've just checked another tag check a few hours later PR was merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/280)
=> AES-GCM: constant time tag check

tlslite/extensions.py
Fix few style issues in the extensions module, simplify code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/282)
=> Bit of maintenance in the extensions module

tlslite/utils/python_tripledes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/295)
=> add missing metadata to pure python implementation object

.travis.yml, Makefile, build-requirements-2.6.txt, build-requirements-2.7.txt, build-requirements-3.2.txt, build-requirements-3.3.txt, tests/tlstest.py, tlslite/utils/python_rsakey.py
backport https://github.com/tomato42/tlslite-ng/pull/297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/299)
=> Backport RSA multithreading fix

.travis.yml
use the non-beta version of python 3.7, do full matrix on 3.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/283)
=> make python 3.7 official

tests/tlstest.py, tlslite/constants.py, tlslite/extensions.py, tlslite/handshakesettings.py, tlslite/messages.py, tlslite/messagesocket.py, tlslite/tlsconnection.py, tlslite/tlsrecordlayer.py, tlslite/utils/format_output.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_handshakesettings.py, unit_tests/test_tlslite_messages.py, unit_tests/test_tlslite_tlsrecordlayer.py
Adds heartbeat extension and unit tests for it.
Fixes #58 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/155)
=> Heartbeat extension

tlslite/tlsconnection.py
When tlslite-ng detected invalid key-share, undefined variable was used.
This PR should fix that and implement correct handling of key-share.
fix for testing https://github.com/tomato42/tlsfuzzer/issues/364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/310)
=> fix handling of invalid key-share

scripts/tls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/326)
=> fix tls.py client compatibility with python 3

tlslite/tlsconnection.py, unit_tests/test_tlslite_tlsconnection.py
Exporters are calculated diffently in TLS1.3 add support according to
RFC8446 Section 7.5
Fixes #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/328)
=> Add TLS1.3 Exporters support

Makefile
the test server and client need to work on all the python versions we
support so actually test them on those versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/332)
=> run simple test for tls.py too

build-requirements-3.3.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/348)
=> freeze more py3.3 build requirements

README, README.md
fix typo and add changes implemented since the last changelog update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/349)
=> add library changes to README

.travis.yml
fixes #364
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/369)
=> Remove python3.2 from Travis config

scripts/tls.py
Add --cipherslist switch to enable non-default ciphers in tls.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/374)
=> Add --cipherslist switch

README.md, tlslite/__init__.py
Add the badge with link to documentation and few minor fixes in docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/392)
=> RtD badge/docs fixes

tlslite/messages.py, tlslite/tlsrecordlayer.py, tlslite/utils/codec.py
Fixes #212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/394)
=> If parsing of the certificate fails throw BadCertificate error

tlslite/tlsconnection.py
This fixes #306 
This PR adds only the client side checks. The server side was added with #324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/396)
=> Enable client downgrade protection mechanism

tlslite/keyexchange.py, tlslite/mathtls.py, tlslite/recordlayer.py, tlslite/tlsconnection.py, tlslite/utils/deprecations.py, unit_tests/test_tlslite_mathtls.py, unit_tests/test_tlslite_tlsrecordlayer.py, unit_tests/test_tlslite_utils_deprecations.py
Move the code from calcExtendedMasterSecret(), calcMasterSecret(), calcFinished(), _calcKeyBlock() to one place.
fixes #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tomato42/tlslite-ng/398)
=> [WIP]Move keying material extractors to one place

.travis.yml, setup.py, tests/tlstest.py
add testing on 3.8 on the 0.7.x branch
depends on #422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/433)
=> add Python 3.8 CI [0.7]

.travis.yml, setup.py, tlslite/integration/imap4_tls.py
Test 0.7.x branch on Python 3.9 too
depends on #433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/435)
=> Add testing on python 3.9 [0.7]

.github/workflows/ci.yml, build-requirements-2.6.txt, build-requirements-3.3.txt
Add Actions-based CI with coveralls submission using coveralls-python tool
fixes #444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/450)
=> Add Github Actions based CI (coveralls-python submitter)

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/455)
=> Try fixing the merge build task for coveralls

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/456)
=> use badge from GitHub Actions Workflow

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/460)
=> make codeclimate work for external PRs too

build-requirements-3.3.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/477)
=> fix CI on py3.3

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/476)
=> add Python 3.10 to CI

build-requirements.txt, tlslite/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/478)
=> add max_fragment_length extension id

scripts/tls.py
To verify if the script added in https://github.com/tlsfuzzer/tlsfuzzer/pull/762 works as expected, we need an echo server in tlslite-ng, so add it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/480)
=> Add echo capability to the example server

tlslite/extensions.py, tlslite/messages.py, unit_tests/test_tlslite_extensions.py, unit_tests/test_tlslite_messages.py
update few `str()` magic methods to make the described object easier to interpret
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/494)
=> More readable str() of ClientHello

tlslite/messages.py, unit_tests/test_tlslite_messages.py
fixes #489
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/497)
=> reject too long session_id field

tests/tlstest.py, tlslite/constants.py, tlslite/handshakesettings.py, tlslite/tlsconnection.py
A simple fix #213 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/498)
=> Automatically select SHA256 PRF ciphers if that are the only PSKs we have

tlslite/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/526)
=> add brainpool identifiers from RFC8734

.github/workflows/ci.yml, tlslite/basedb.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/545)
=> add py3.13 to CI
